=== benad/azbenadmestatic/public/page.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://benad.me/schema/page"
    xmlns:page="http://benad.me/schema/page"
    elementFormDefault="qualified">
    <xsd:element name="page">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="page:head"/>
                <xsd:element ref="page:body"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="body">
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded" minOccurs="0">
                <xsd:element ref="page:section"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="head">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" name="title" type="xsd:string"/>
                <xsd:element name="id" type="xsd:ID"/>
                <xsd:element name="meta" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:choice maxOccurs="unbounded" minOccurs="0">
                            <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="section">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element ref="page:p"/>
                <xsd:element ref="page:codeblock"/>
                <xsd:element ref="page:img"/>
                <xsd:element ref="page:subsection"/>
                <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
            </xsd:choice>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="subsection">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element ref="page:p"/>
                <xsd:element ref="page:codeblock"/>
                <xsd:element ref="page:img"/>
                <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
            </xsd:choice>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
            <xsd:attribute name="href" type="xsd:anyURI" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:simpleType name="codeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="bash"/>
            <xsd:enumeration value="shell"/>
            <xsd:enumeration value="c"/>
            <xsd:enumeration value="cpp"/>
            <xsd:enumeration value="diff"/>
            <xsd:enumeration value="groovy"/>
            <xsd:enumeration value="javascript"/>
            <xsd:enumeration value="java"/>
            <xsd:enumeration value="perl"/>
            <xsd:enumeration value="plain"/>
            <xsd:enumeration value="html"/>
            <xsd:enumeration value="xml"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:element name="codeblock">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" type="page:codeType" use="optional"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="img">
        <xsd:complexType>
            <xsd:attribute name="src" type="xsd:anyURI" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="p" type="page:spanType"/>
    
    <xsd:complexType mixed="true" name="spanType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="span" type="page:spanType"/>
            <xsd:element name="i" type="page:spanType"/>
            <xsd:element name="b" type="page:spanType"/>
            <xsd:element name="tt" type="page:spanType"/>
            <xsd:element name="a">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="href" type="xsd:anyURI" use="required"/>
                            <xsd:attribute name="title" type="xsd:string" use="optional"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
        </xsd:choice>
    </xsd:complexType>
</xsd:schema>

=== benad/azbenadmestatic/content/articles.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>Articles</title>
        <id>articles</id>
    </head>
    <body>
        <section>
            <p>Here are a few articles that I wrote.</p>
            <subsection title="ed, or How I Learned To Love The Mouse" href="ed.xml">
                <p>A closer look at a programmer's choice of a text editor software.</p>
            </subsection>
            <subsection title="What is Software Design" href="software_design.xml">
                <p>The one with the missing punctuation. An introductary look at design in programming and software development.</p>
            </subsection>
            <subsection title="Why Are You A Programmer?" href="why_programming.xml">
            	<p>What makes people become programmers? A humorous list of patterns I've noticed...</p>
        	</subsection>
            <subsection title="A Case for Software Architects" href="case_architect.xml">
            	<p>Trying to define the role of a software architect in large software development projects.</p>
        	</subsection>
        </section>
    </body>

</page>
