=== benad/azbenadmestatic/public/page.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://benad.me/schema/page"
    xmlns:page="http://benad.me/schema/page"
    elementFormDefault="qualified">
    <xsd:element name="page">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="page:head"/>
                <xsd:element ref="page:body"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="body">
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded" minOccurs="0">
                <xsd:element ref="page:section"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="head">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" name="title" type="xsd:string"/>
                <xsd:element name="id" type="xsd:ID"/>
                <xsd:element name="meta" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:choice maxOccurs="unbounded" minOccurs="0">
                            <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="section">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element ref="page:p"/>
                <xsd:element ref="page:codeblock"/>
                <xsd:element ref="page:img"/>
                <xsd:element ref="page:subsection"/>
                <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
            </xsd:choice>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="subsection">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element ref="page:p"/>
                <xsd:element ref="page:codeblock"/>
                <xsd:element ref="page:img"/>
                <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
            </xsd:choice>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
            <xsd:attribute name="href" type="xsd:anyURI" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:simpleType name="codeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="bash"/>
            <xsd:enumeration value="shell"/>
            <xsd:enumeration value="c"/>
            <xsd:enumeration value="cpp"/>
            <xsd:enumeration value="diff"/>
            <xsd:enumeration value="groovy"/>
            <xsd:enumeration value="javascript"/>
            <xsd:enumeration value="java"/>
            <xsd:enumeration value="perl"/>
            <xsd:enumeration value="plain"/>
            <xsd:enumeration value="html"/>
            <xsd:enumeration value="xml"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:element name="codeblock">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" type="page:codeType" use="optional"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="img">
        <xsd:complexType>
            <xsd:attribute name="src" type="xsd:anyURI" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="p" type="page:spanType"/>
    
    <xsd:complexType mixed="true" name="spanType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="span" type="page:spanType"/>
            <xsd:element name="i" type="page:spanType"/>
            <xsd:element name="b" type="page:spanType"/>
            <xsd:element name="tt" type="page:spanType"/>
            <xsd:element name="a">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="href" type="xsd:anyURI" use="required"/>
                            <xsd:attribute name="title" type="xsd:string" use="optional"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
        </xsd:choice>
    </xsd:complexType>
</xsd:schema>

=== benad/azbenadmestatic/content/me_not.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>What I'm Not</title>
        <id>me_not</id>
    </head>
    <body>
        <section>
            <p>Before you jump to conclusions about who I am, I'd like to take
            some time to make sure I'm not incorrectly mislabelled as
            one of the following personality types.</p>
        </section>
        <section title="A Nerd">
            <p>I am not a "Nerd", that is someone obsessed with intellectualism.
            That is, even though I can quickly learn, I don't enjoy knowledge
            <i>per se</i>, nor pride myself for it.</p>
            <p>I don't enjoy reading books. I don't like remembering seemingly
            random facts. I don't like puzzles. And I <i>definitely</i> dislike
            chess.</p>
            <p>True, I may have some affinity with nerds, including being smart,
            slighly socially akwards and not liking sports (no, chess is
            <i>not</i> a sport). But having met and been friends with some
            <i>real</i> nerds many times, I can tell that there's still a
            difference between me and "them".</p>
            <p>I think one characteristic that I have and that few "proper"
            nerds don't have is that I am pragmatic. I don't learn something
            unless it can be useful through me or to teach to others. I find
            abstract thoughts and mind games absurd. I don't particularly like
            the idea of research in mathematics unless a specific potential
            application is thought of before hand.</p>
            <p>In a way, I may be a slightly "nerdy" engineer. Think of me of a
            non-<i>blas√©</i> Dilbert.</p>
        </section>
        <section title="A Geek">
            <p>I am not a geek. That is, I don't particularly like any of the
            following:
                <html:ul>
                    <html:li>Star Trek</html:li>
                    <html:li>Star Wars</html:li>
                    <html:li>Almost all TV-based American science
                    fiction</html:li>
                    <html:li>Japanese animation, with a few exceptions</html:li>
                    <html:li>Lord of the Rings, and all its derivatives,
                    including World of Warcraft and most MMORPG</html:li>
                    <html:li>Most video games</html:li>
                </html:ul>
            </p>
            <p>And so on. True, I like gadgets <i>a bit</i>, but only as long
            as I actively
            use them. I like some science fiction. And some Japanese animation.
            And some video games. But let's be clear: I'm highly selective. Like
            everything else, 
            <a href="http://en.wikipedia.org/wiki/Sturgeon%27s_Law">90% of
            everything is crap</a>. And I'm not going to focus my attention
            only on things that make me escape from reality.</p>
        </section>
        <section title="An Apple Fan">
            <p>And I'm not an Apple fan. Yes, I own only Macs. And an Apple
            mouse. And an iPhone. And I prefer Macs. And a lot of Apple
            products.</p>
            <p>But let me be clear. Every day of work I make use of Mac, Windows
            and Linux at the same time. I can assemble a PC from parts and
            install Linux on it. I've been using Windows since Windows NT 4. I
            may generally dislike Microsoft Windows, but I often prefer using
            some Linux or Solaris distribution rather than Mac OS X. Most of the
            applications I use are 100% cross-platform. I dislike DRM, even
            when Apple-branded. I don't like how the iPhone platform is closed.
            I always prefer open-source over the amount of features and
            "support".</p>
            <p>I just prefer Macs in general, and don't mind paying for an
            extra bit of quality and warranty.</p>
            <p>And, really, Microsoft tends to annoy me in the way they make
            their software. At least with open-source I can fix it.</p>
        </section>
    </body>

</page>

=== benad/azbenadmestatic/src/me.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/2.5/ca/
    -->
    
    <head>
        <title>About Me</title>
        <id>me</id>
    </head>
    <body>
        <section>
            <p>This section is about me, Benoit Nadeau. While it always feels
            strange to talk about oneself, and worse, someone else's
            narcissistic rant, I'll try my best to make these pages as
            entertaining as possible.</p>
            <subsection title="Benad?" href="me_benad.xml">
                <p>What is the origin of the strange nickname "Benad"?</p>
            </subsection>
            <subsection title="What I'm not" href="me_not.xml">
                <p>What you assume I am, but if you start to know me, am <i>not</i>.</p>
            </subsection>
            <subsection title="Autobiography" href="me_bio.xml">
                <p>A short autobiography of some kind.</p>
            </subsection>
        </section>
        
    </body>

</page>

=== benad/azbenadmestatic/content/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>Welcome</title>
        <id>index</id>
        <meta>
            <html:link rel="alternate" type="application/rss+xml" title="RSS" href="//feeds.feedburner.com/benadme" />
        </meta>
    </head>
    <body>
        <section>
            <p>Welcome to my little humble home on the Internet. This place is
            about me, Benoit Nadeau, also known by the alias Benad. It is also a
            hub for my various Internet activites and interests.</p>
        </section>
        <section title="Updates">
            <subsection title="June 13, 2026">
                <p>Added the article <a href="meta_simplifications.xml">Simplifications</a>, about the way I simplified the building and deployment of this web site.</p>
            </subsection>
            <subsection title="February 12, 2022">
                <p>Posts are regularly added to the <a href="/blog/">blog</a>, including a new series about modern CLI tools.</p>
            </subsection>
            <subsection title="January 18, 2018">
                <p>This site is now <a href="/blog/2016/09/12/https-the-new-standard/">using HTTPS</a> and <a href="/blog/2017/10/12/hello-ipv6/">supports IPv6</a>.</p>
            </subsection>
            <subsection title="April 26, 2016">
                <p>Added <a href="meta_blog.xml">The Static Blog</a>, about the relocation of my blog to this site.</p>
            </subsection>
            <subsection title="December 6, 2015">
                <p>Added the article <a href="case_architect.xml">A Case for Software Architects</a>, where I try to define the software architect role in a software development project.</p>
            </subsection>
            <subsection title="June 30, 2014">
                <p>Added the article <a href="why_programming.xml">Why Are You A Programmer?</a>, listing humorous stereotypes of the various kind of programmers.</p>
            </subsection>
            <subsection title="August 4, 2013">
                <p>This web site is now written in HTML5. More information in the article <a href="meta_html5.xml">The Future is HTML5</a></p>
                <p>Also, I corrected countless grammatical errors all over the place, but hopefully nobody noticed.</p>
            </subsection>
            <subsection title="June 3, 2012">
                <p>First, my blog moved (again) to the permanent URL <a href="https://blog.benad.me">blog.benad.me.</a></p>
                <p>Second, I added the article "<a href="software_design.xml">What is Software Design</a>".</p>
            </subsection>
            <subsection title="March 4, 2012">
                <p>Since January 2012 I'm posting daily on my <a href="http://benad-blog.posterous.com/">Posterous blog</a>.</p>
            </subsection>
            <subsection title="October 9, 2010">
                <p>Added article <a href="ed.xml">ed, or How I Learned To Love The Mouse"</a>
                and cleaned up the site a bit.</p>
            </subsection>
            <subsection title="March 1, 2010">
                <p>Completed <a href="meta_present.xml">About This Site - The Present</a>
                and <a href="meta_future.xml">About This Site - The Future</a>.
                Hopefully I'll update this site at a faster pace in the following
                weeks.</p>
            </subsection>
            <subsection title="September 3, 2009">
                <p>Added the page <a href="meta_past.xml">About This Site -
                The Past</a> and a (manually crafted, for now) <a
                href="//feeds.feedburner.com/benadme">RSS feed</a>.</p>
            </subsection>
            <subsection title="August 23, 2009">
                <p>Initial release. For now, only the "<a href="me.xml">About
                Me</a>" section is complete, but at least it's a start.</p>
            </subsection>
        </section>
        <section title="Menu">
            <p>The site is broken up in the following sections. More sections
            will be added in the future if needed.</p>
            <subsection title="About Me" href="me.xml">
                <p>Find out more about who is Benad. This could be quite boring
                and overwhelmingly narcissistic, so feel free to move on to
                another section.</p>
            </subsection>
            <subsection title="About This Site" href="meta.xml">
                <p>Learn about the making of this site. Can get technical at
                times. Interesting if you like reading a web site describing
                itself.</p>
            </subsection>
            <subsection title="Articles" href="articles.xml">
                <p>Long-winded rants or thoughts about things, when they are too
                big to fit in my blog.</p>
            </subsection>
            <subsection title="Links" href="links.xml">
                <p>Various references to my Internet activities.</p>
            </subsection>
        </section>
    </body>

</page>

=== benad/azbenadmestatic/content/meta_future.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>About This Site - The Future</title>
        <id>meta_future</id>
    </head>
    <body>
        <section>
            <p>Well, there isn't much more to say for now, apart from trying to focus as much as possible on the content of this web site.</p>
            <p>As I write the web site, I continually adapt my XSD and XSLT template to match new XML tags I come up to help me write the contents. As a "catch-all" fallback, I've left the possibility for me to write raw HTML tags in my XML documents, though over time these will be replaced with my custom-made tags (with eerily similar names to their HTML counterparts).</p>
            <p>Also, I may have to struggle a bit to make my web pages more "accessible" to disabled users, and potentially also some of those text-to-speech technologies. My understanding is that they would easily break on my XML code, though the static HTML pages I generate as a fallback should work fine. How to test?</p>
            <p>Finally, even though I currently think I "nailed" making my web pages gracefully degrade on smaller and less powerful browsing devices, I could still make my pages render specifically for some browsers like Opera Mini or the mobile Safari used on the iPhone.</p>
        </section>
    </body>

</page>

=== benad/azbenadmestatic/content/meta_blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">

    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->

    <head>
        <title>The Static Blog</title>
        <id>id</id>
    </head>
    <body>
<section title="History">

<p>I've moved from one blogging platform to another four times in the past 14 years. This isn't unusual, as many hop from one service to another depending on what's trendy or where their social circles reside. In my case, I've never used blogs for social networking, instead looking for some kind of stable environment where blogging would be convenient and simple.</p>

<p>I started on <a href="https://slashdot.org/">Slashdot</a> journals around November 2002, during my last year of university (my 6th year of post high school studies). That environment was clearly an afterthought of the Slashdot service and didn't feel much like a proper blogging service. A modern-day equivalent would be to start your own "<a href="https://en.wikipedia.org/wiki/Reddit#Subreddits">subreddit</a>" on <a href="https://www.reddit.com/">Reddit</a>, and make a new post for each blog post. Slashdot is first and foremost a news link service with powerful commenting abilities, so it has quite an added complexity compared to what should have been a simple blogging service.</p>

<p>I restarted from scratch my "proper" blog <a href="http://benad.me/blog/2005/9/7/so-what-is-this-all-about/">on September 2005</a> on <a href="http://www.livejournal.com/">LiveJournal</a>. For a little while I even paid for the premium service, though it was useless for me beyond some advanced site template features. The site looked horrible (but whose LiveJournal blog looked good?), and posting to it on anything but a desktop web browser wasn't convenient.</p>

<p>In <a href="http://benad.me/blog/2010/7/1/our-national-moving-day/">July 2010</a> I moved to <a href="https://en.wikipedia.org/wiki/Posterous">Posterous</a>, a blogging service that was first designed to make it easy to post anything by email. It is also the first service I used that supported <a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a>. It was incredibly convenient, simple to use, and the blog looked great. One major downside: This was a tech startup, that unlike Slashdot and LiveJournal was short-lived. The service <a href="https://en.wikipedia.org/wiki/Posterous#Shutting_down_Posterous_and_building_PostHaven">shut down</a> two years later.</p>

<p>That time, I got frustrated at moving the URL location of my blog from one place to another, and thought of a more long-term solution. First, I was already in the process of building my web site on my own personal domain <a href="http://benad.me/">benad.me</a>, so I decided to move to a proper, commercial blog hosting service that would support personal domains, in my case <a href="http://blog.benad.me/">blog.benad.me</a>. The service <a href="https://www.squarespace.com/">Squarespace</a> looked trouble-free, with dedicated apps for posting and great-looking templates. A bit expensive, though. Also, its software upgrades <a href="http://benad.me/blog/c2c3ffc1-c0ba-4f65-97ba-7f1029839e5e/">were far from trouble-free</a>. Over time, it was difficult to justify the cost and trouble for what amounted to a simple blog, as Squarespace oriented themselves (and their site templates) towards small e-commerce and design portfolios.</p>

</section>
<section title="Issues">

<p>Over the years, I've had several concerns about using 3rd-party blogging services instead of self-hosting my own solution:</p>

<html:ul>
<html:li>The hosting service could go away. Now, I admit that LiveJournal, and even Slashdot, are shockingly still up and running after all those years, something unusual for free web services after 15 years. Still, I got badly burned with Posterous, and anything that doesn't have a clean process to export your entire blog from day one, and not as a favour days before the service permanently closes, is risky.</html:li>
<html:li>The hosting service can be insecure. Luckily, it wasn't the case for me, but anything resembling <a href="https://wordpress.org/">Wordpress</a>, or countless PHP-based CMS like <a href="https://en.wikipedia.org/wiki/Joomla">Joomla</a> require constant security patches, and are the target of hackers.</html:li>
<html:li>Content ownership can be a grey area. Sure, you own the original copyright of your posts, but for the service to work you have to grant them some redistribution rights, at minimum to let them host your content. Over the years, licensing gives those companies greater latitude in selling that content, especially on free hosting services.</html:li>
<html:li>Finally, the posts' URLs are unstable. A link to one of my blog post on service X might not work a few years later. I want to use a solution that will give reliable URLs in the future, regardless of my decision of where of how I would host it.</html:li>
</html:ul>

</section>
<section title="A Static Blog">

<p>The long-term solution would be to host my blog myself alongside my main web site, yet how can I do that if I want to avoid hosting dynamic content and worry about security?</p>

<p>Actually, why do hosting a web blog assume that the content has to be dynamically generated by the web server on demand? Surely there are offsite static blog generators that can build up a collection of generated web pages from some blog "source", and from there I can simply copy over the static pages on my web server.</p>

<p>My main site is already using some static template system, but doesn't have any of the logic necessary for presenting many pages in a blog-like structure. I could either code that myself, or use <a href="https://staticsitegenerators.net/">another blog generator tool</a>.</p>

<p>Sure, I lose the ability of posting directly using my phone, since I have to regenerate my blog static pages from a computer and then upload that, but over the years I rarely posted a final, unreviewed post from my phone anyway. Also, I would lose blog commenting, unless I use some 3rd-party JavaScript option that injects a comment section dynamically over my otherwise static blog pages.</p>

<p>I ended up using <a href="https://gohugo.io/">Hugo</a>, a static web site generator written in <a href="https://golang.org/">Go</a> that has powerful template-building features and supports anything that's needed for a blog. It has enough flexibility to generate my blog pages with the exact same HTML structure as the rest of my web site, making its integration seamless. As for commenting, I used <a href="https://disqus.com/">Disqus</a>.</p>

</section>
<section title="The Last Import">

<p>Moving from Squarespace to Hugo took a few days of effort. Squarespace's only export format was something that was compatible with Wordpress which is a large XML document, while Hugo expects blog posts to be in one individual HTML or Markdown document per post. For some reason, Squarespace's export doesn't contain the original Markdown I used for each post, even though it's still accessible on their web site, so technically their export tool isn't complete.</p>

<p>So I wrote my own Python script to parse the XML and dump out individual HTML posts for Hugo. There were a few adjustments to be made to the XML. The post creation times were in <a href="https://en.wikipedia.org/wiki/Coordinated_Universal_Time">UTC</a>, so I had to adjust them to my time zone (including daylight savings time transitions) using the <a href="http://pythonhosted.org/pytz/">pytz Python module</a>. The URLs had to be adjusted with Hugo's structure, but I couldn't replicate it 100% (especially during the times Squarespace mangled my post URLs), so for a few posts I had to resort to server-side HTTP redirection rules. Ultimately, I was able to test out every single URL to make sure they worked in the new environment.</p>

<p>Similarly, the URLs in Squarespace's XML export had to be adjusted for Disqus' import tool so that they match the new Hugo URLs properly.</p>

<p>In the end, it all works well. The Hugo templates and CSS could be adjusted to fit better the rest of the site, but otherwise it's fully functional, including the RSS feed. I placed all my scripts and tools in <a href="https://bitbucket.org/">Bitbucket</a>, and since Hugo can be installed by downloading a single binary file, it's easy to replicate the environment on any other machine.</p>

<p>In the future I may even use Hugo to replace my own aging XSLT template system for the rest of my web site, but then I wouldn't be able to brag about creating my own custom template system anymore.</p></section>

</body>
</page>
