=== benad/azbenadmestatic/public/page.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://benad.me/schema/page"
    xmlns:page="http://benad.me/schema/page"
    elementFormDefault="qualified">
    <xsd:element name="page">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="page:head"/>
                <xsd:element ref="page:body"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="body">
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded" minOccurs="0">
                <xsd:element ref="page:section"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="head">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element minOccurs="0" name="title" type="xsd:string"/>
                <xsd:element name="id" type="xsd:ID"/>
                <xsd:element name="meta" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:choice maxOccurs="unbounded" minOccurs="0">
                            <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="section">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element ref="page:p"/>
                <xsd:element ref="page:codeblock"/>
                <xsd:element ref="page:img"/>
                <xsd:element ref="page:subsection"/>
                <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
            </xsd:choice>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="subsection">
        <xsd:complexType>
            <xsd:choice maxOccurs="unbounded">
                <xsd:element ref="page:p"/>
                <xsd:element ref="page:codeblock"/>
                <xsd:element ref="page:img"/>
                <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
            </xsd:choice>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
            <xsd:attribute name="href" type="xsd:anyURI" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:simpleType name="codeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="bash"/>
            <xsd:enumeration value="shell"/>
            <xsd:enumeration value="c"/>
            <xsd:enumeration value="cpp"/>
            <xsd:enumeration value="diff"/>
            <xsd:enumeration value="groovy"/>
            <xsd:enumeration value="javascript"/>
            <xsd:enumeration value="java"/>
            <xsd:enumeration value="perl"/>
            <xsd:enumeration value="plain"/>
            <xsd:enumeration value="html"/>
            <xsd:enumeration value="xml"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:element name="codeblock">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="type" type="page:codeType" use="optional"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="img">
        <xsd:complexType>
            <xsd:attribute name="src" type="xsd:anyURI" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="p" type="page:spanType"/>
    
    <xsd:complexType mixed="true" name="spanType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="span" type="page:spanType"/>
            <xsd:element name="i" type="page:spanType"/>
            <xsd:element name="b" type="page:spanType"/>
            <xsd:element name="tt" type="page:spanType"/>
            <xsd:element name="a">
                <xsd:complexType>
                    <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                            <xsd:attribute name="href" type="xsd:anyURI" use="required"/>
                            <xsd:attribute name="title" type="xsd:string" use="optional"/>
                        </xsd:extension>
                    </xsd:simpleContent>
                </xsd:complexType>
            </xsd:element>
            <xsd:any namespace="http://www.w3.org/TR/xhtml1/strict" processContents="lax"/>
        </xsd:choice>
    </xsd:complexType>
</xsd:schema>

=== benad/azbenadmestatic/content/me_bio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>Autobiography</title>
        <id>me_bio</id>
    </head>
    <body>
        <section>
            <p>This is not a proper biography <i>per se</i>, since most personal
            stuff is left out. Here is more about things of my past that might
            be of interest to the general public.</p>
        </section>
        <section title="The Age of Music">
            <p>My early childhood is, outside the confines of my family home,
            relatively un-eventful, until the middle of the first grade of elementary
            school. After an odd "auditory test", where students would be asked
            to compare the pitch of music notes, my parents were presented with
            two choices about my academic future. The first was, given my early
            academic results, to skip two years of school directly to grade 4.
            Since I was already the smallest student in first grade, such
            prospect, in a public school, would have been physically hazardous
            for me. The second was for me to start attending a public school for
            academically and musically gifted students. Feeling my boredom and fear
            of retribution from taller students, my parents obviously chose the
            latter choice.</p>
            <p>From then, I spent roughly half of my school time learning and
            playing music, and so on until the end of high school. My
            specialization was the violin. That always was quite a physical
            challenge due to its unforgiveness and my lack of precise finger
            movement. I since then stopped playing music, with some regret.</p>
            <p>Yet, beyond the theory and the endless hours of physical
            practice and pain, I learned from music many things that shaped me.
            Such things are difficult to describe here, but suffice to say that
            whatever would interest me from then on, I would be <i>artful</i>
            at it.</p>
        </section>
        <section title="Discovering a Talent">
            <p>It is difficult to say with humility that you are genuinely
            talented at something. But if you are, regardless of how much effort
            it would take to grow in such talent, that domain always feels
            easy and natural. For me, it was anything related to computer
            software.</p>
            <p>Early on, my mother discovered that "gadgets" would fascinate me.
            Discovering how a tool of object works would fill me with passion,
            that is until I understood of it worked. The problem though was with
            my overall clumsiness with physical objects (which also affected my
            learning of violin). But with software, learning was
            <i>limitless</i> and unaffected by physical akwardness.</p>
            <p>Me and my mother will always remember my first encounter with a
            <i>Macintosh</i> computer. Busy at work and with no access to a
            babysitter, she knew that I was old enough to "take care of myself"
            in her office while she went teaching at the university for the
            next hour or so. The
            only piece of "entertainment" was a Macintosh computer with the
            "Mac Draw" software loaded and the general instruction "have fun
            drawing pictures". And, without any instruction or prior training,
            so did I. And played with the system settings. And, out of many
            things, changed the desktop pattern, which was the only thing I
            haven't properly reverted before she came back. Which prompted
            my mother to ask me how I did it.</p>
            <p>Unlike the other "PCs" I've seen after, nothing felt as intuitive
            and limitless as a Macintosh. While this was true for most people,
            for me this meant I would learn about the software easily and
            at a high pace.</p>
        </section>
        <section title="A Proper Profession">
            <p>Now then, there isn't anything special about being good at
            <i>using</i> software. Understanding how it
            works, maybe. Reverse-engineering it, maybe a bit more.
            But developing good software based on a deep
            understanding and appreciation for high quality software, now that's
            difficult. So being talented enough to design and develop <i>great</i>
            software in a way that seems, to the casual observer, both easy and
            "like magic", now <i>that's</i> something special enough to be
            considered a talent. But how can you know if you have such talent
            in something?</p>
            <p>It took quite a leap of faith to try, on my own and with limited
            understanding of the English language, "real" programming before
            finishing college. And even up to the end of the 90s, "programmers"
            were not as such in high demand as it is now. But after some
            practice, I could say that I liked it and was good enough to
            potentially make software development a lifelong profession, even
            without high demand or high pay.</p>
            <p>So I was surprised to see this "information age" arrive so fast,
            and lucky enouch to be in a profession with such high demand.
            Even if I were to be lazy and just coast off my talent, I <i>like</i>
            writing good software, even more when other people can appreciate
            it. So even with talent, I'm still a slave to my "art".</p>
        </section>
        <section title="The Rest">
            <p>What happened during University and later is, unless I become a
            celebrity of some kind, unworthy of much attention. Suffice to say
            that while my life is sometimes very difficult, it is still
            relatively <i>cozy</i>. Enough for me to have the time to write
            this.</p>
            <p>This is when one would normally think about what kind of
            achievements would define their life. Or what one would like to
            experience before death.</p>
            <p>But I don't. <i>Toughtful passion</i> simply drives me.</p>
            <p>... Or something pretentious like that.</p>
        </section>
        
    </body>

</page>

=== benad/azbenadmestatic/content/me_benad.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>Benad?</title>
        <id>me_benad</id>
    </head>
    <body>
        <section>
            <p>So, why the nickname "Benad"? Well, to explain that, I first need
            to start with the ethymology of my real name, Benoit
            Nadeau.</p>
        </section>
        <section title="Benoit Nadeau">
            <p>My first and last name are unusual. Yes,
            here in Québec, both the given name "Benoit" and the surname
            "Nadeau" are quite usual.</p>
            <p>To put things in context, in Québec many women would simply
            keep their surname after marriage, which would save paperwork
            and confusion after divorce. To avoid "sexism", or fights,
            parents would often would give <i>both</i> their unchanged
            surnames to their kids. Of course, the order of such compound
            surname could be the source of a fight too, and no one properly
            thought ahead of what would happen in the next generation.</p>
            <p>So, for me, I got my mother's surname, "Benoit", and my
            father's surname "Nadeau". And since "Benoit" can be both a
            surname and given name, it became my given name. Don't worry,
            my sibblings only got "Nadeau" as surnames, keeping a bit of
            "tradition"...</p>
        </section>
        <section title="The Circumflex Accent">
            <p>But then, I'm not totally forthcoming about my name.
            Officially, my name is "BENOIT JEAN LOUIS-OLIVIER NADEAU",
            written with a cheap typewriter at the mayor's office. Years
            later, that was "translated" officially to "Benoît Jean
            Louis-Olivier Nadeau". Notice that circumflex accent (the accent
            "^") on the "i" that just appeared out of nowhere.</p>
            <p>Well, I personally don't care about the circumflex accent,
            even though officially I was given one by the
            government. Why? Well, a bit of ethymology about the name "Benoit".
            </p>
            <p>"Benoit" is an old Latin name that dates back to the 13th
            century, from the word "benedictus", or "blessed". Its original
            French form was "Benoist", which sounds like "buh-no-east".
            Later, the "s" became silent, so it sounded like "buh-no-it". To
            separate the vowels "o" and "i" in the sound, a circumflex
            accent was added on the "i". In modern French though the name
            now sounds like "be-n-wa", so eventually the accent will be
            dropped altogether, but depending of use (given versus surname,
            lineage, region, etc.) the accent remains. And that's what
            the government "guessed".</p>
            <p>So, let me be clear: officially it's "Benoît", usually it's
            "Benoit", and it sounds like "be-n-wa". And I quickly learned
            from Anglophones that have no knowledge of French that they would
            almost always say "ben-oy-t", which sounds horrible, so I had
            to do <i>something</i>...</p>
        </section>
        <section title="Benad">
            <p>The "compromise" for Anglophones in the form of "Benad" came
            as an unintended consequence of me trying to figure out what my
            Internet nickname should be.</p>
            <p>It was still the early 90s when I realized of the importance
            of the name you give to yourself for your "main" online
            personality. More than that, I forsaw that finding a unique
            name would just be harder over time as everybody became more
            "connected".</p>
            <p>So, I connected the first three letters of my given name to
            the first three letters of my surname. And it sounded good in
            English. So I kept it.</p>
            <p>Well, it's still not totally unique since "Benad" is a real
            given name. But if I'm lucky enough, nobody registered it before I
            do.</p>
            <p>And what about the "84" I add when somebody else already
            registered "benad"? No, it's not my birth year (I wish). It's
            because the novel "1984" was one of the first English novel I've
            read, so I kept using "84" as a suffix.</p>
        </section>
        
    </body>

</page>

=== benad/azbenadmestatic/content/meta_simplifications.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>About This Site - Simplifications</title>
        <id>meta_simplifications</id>
    </head>
    <body>
        <section>
            <p>Since 2023, I simplified the building and deployment of this web site.</p>
            <subsection href="/blog/2023/03/04/the-static-web-site-server/" title="The Static Web Site Server">
                <p>I stopped hosting this site on my own Linux virtual machine, and instead used Azure Static Web App, a free alternative.</p>
            </subsection>
            <subsection href="/blog/2023/06/11/it-goes-to-11-from-hugo-to-11ty/" title="It Goes to 11: From Hugo to 11ty">
                <p>This site is now fully generated by 11ty, within a GitHub Action that both builds and deploys the site each time a change is pushed to my Git repository's main branch.</p>
            </subsection>
            <subsection href="/blog/2026/03/06/oat-and-ai/" title="Oat and AI">
                <p>With some assistance from GitHub Copilot, I replaced this site's CSS using Bootstrap with Oat.</p>
            </subsection>
        </section>
    </body>

</page>

=== benad/azbenadmestatic/content/case_architect.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">

    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->

    <head>
        <title>A Case for Software Architects</title>
        <id>case_architect</id>
    </head>
    <body>
<section title="Introduction">

<p>Large software development projects really magnify every part of the process, to the point of work specialization. The most obvious of such specialization is the programmer, but there's also quality assurance, usability, project management, and so on. A lesser known specialization is the software architect.</p>

<p>The software architect role may have been less well defined since not only it overlaps too much with the traditional programming and project management roles, but also because the term "architect, like "engineering", is too often misused only as an indication of seniority.</p>

<p>So it may be worthwhile to properly define "architecture" in the context of software development, since from there it will be easier to see where it fits in the software development process, and how this can lead to the role of software architect.</p>

</section>
<section title="Architecture">

<p>Architecture could be vaguely defined as the "environment" or the "foundation". As such, there are two kinds of environments for software development: The architecture of the software (supporting the code), and the architecture of the software development (supporting the developers).</p>

<p>The architecture of software is well known, and is pretty much required nowadays. Above the firmware, we do have the entire operating system stack, and above that a rich environment of APIs and software development libraries. Not only these reduce significantly the amount of development time, but can also give the software some assurances: Isolation and reporting when your software crashes, security and isolation, logs and performance metrics, and so on.</p>

<p>The architecture of software development is more about the environment and tools used to make software development easier beyond simple code reuse. Those include compilers, linkers and IDEs for programming proper, but also a plethora of tools that help in collaborating within a team of developers, such as bug and work trackers, version control systems, continuous integration, automated regression testing, documentation tools, and so on.</p>

<p>As you can see, the line between the two kinds of architecture is pretty thin. Ultimately, the "architecture" in software development translate to the set of infrastructure and tools used to facilitate the development process. They are so much part of the "toolbox" needed to start software development that often programmers expect them to be fully ready at the beginning of development. Still, it may be a good idea to explore what happens when the software architecture is lacking in a project.</p>

</section>
<section title="No Architect">

<p>As mentioned before, a software project is likely to be small enough to make software architect role difficult to notice. But given a reasonable size, minimizing its importance or ignoring it can lead to difficult issues, especially if the project grows even bigger over time or lasts for several years.</p>

<p>Without any software architect work, architectural decisions tend to go through the path of least resistance, be it towards familiarity or intuition. This explains well the popularity of software development collaboration services such as <a href="http://sourceforge.net">SourceForge</a>, <a href="https://github.com">GitHub</a>, <a href="https://bitbucket.org/">Bitbucket</a> and so on. In business environments, investing in a new or updated development infrastructure may be too large and risks delaying the beginning of development, thus often whatever old infrastructure already exists is reused. The danger here is that the environment may not be optimal for the project, and waiting for an opportune time to change it may never happen.</p>

<p>On the other end of the spectrum, you have a few brave (or foolish) souls that would prefer or are forced into writing their own tools from scratch. Similarly, writing custom tools from scratch can happen so slowly that it may go unnoticed: A small compilation tool for a very specific scenario may grow enough in functionality to compete with full-featured competitors, yet have so much arcane and required business logic that it become irreplaceable.</p>

<p>Either way, you can see the risks involved in rushing into software development without stepping back a little bit and figure out if that's the best environment for that project, be it early in the project or when it gains significantly in size.</p>

</section>
<section title="Architecture by Committee">

<p>The lack of an architect in a large software development project tends to disperse clear decisions into negotiated delegation, agreements on the lowest common denominator or feature creep. Recurring themes is those situations are politics of consensus and a limited empathy for the concern of others.</p>

<p>Looking at the specialization of other roles in software development, you can see the causes of those behaviours. Managers see the software architecture either as task delegation and negotiation, while the software tools are seen as Information Technology overhead that should preferably be outsourced. Programmers prefer using technologies they're familiar with, thus sometimes building their own tools seem easier than to learn an external tool. From either's perspective, the quality of the delivered software is often the first thing that gets compromised in the negotiations.</p>

<p>While having a "benevolent dictator" making architectural decisions seems the best way to resolve those conflicting interests, this merely expedites the decision process, while again risking the quality of the software. Instead, let's look at what unique qualities may help in making the best architectural decisions, for all the stakeholders and for the good of the software itself.</p>

</section>
<section title="Architect Qualities">

<p>The most impactful quality is the architect's familiarity with all the roles involved in the development process. Ideally, the architect should be able to do all the tasks in the process, though with any project of significant size and limited budget this would be impractical. At least, this familiarity creates a deep understanding how the architectural decisions impact each task, and from this a better "empathic" decision can be made.</p>

<p>From there, the architect can develop a sense of how much any small thing in the process can have an impact on anything else. A good architect can estimate the impact of the smallest detail in the "big picture" view of the project. This doesn't necessarily translate to perfectionism, as long as the architect can estimate the cost-benefit: Not all details are equally important.</p>

<p>To make good decisions, a good architect should have first hand experience with as many representative options as possible, and be able to tell which options are better in any context. It may even be needed to create brand new solutions. So a good architect must be a quick learner, a good critic, a good decision maker, and also be creative.</p>

<p>Essentially, a good architect must be able to objectively explain why some solution was proposed based on first hand experience, holistic understanding and deep understanding of the domain.</p>

<p>Those qualities seem to be sufficiently unique to warrant a separate role in the software development process. And while the work of an architect may not be as onerous as the other roles in smaller projects, the polyvalence of the architects in their ability to be able to perform other roles allows it to be a temporary or part time role.</p></section>

</body>
</page>

=== benad/azbenadmestatic/content/meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="page.xsl"?>
<page xmlns="http://benad.me/schema/page"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:html="http://www.w3.org/TR/xhtml1/strict"
    xsi:schemaLocation="http://benad.me/schema/page page.xsd">
    
    <!--
    Benad's Web Site by Benoit Nadeau is licensed under a Creative Commons
    Attribution-ShareAlike 4.0 International License
    https://creativecommons.org/licenses/by-sa/4.0/
    -->
    
    <head>
        <title>About This Site</title>
        <id>meta</id>
    </head>
    <body>
        <section>
            <p>This section is a "behind the scenes" of the development of this
            web site.</p>
            <subsection href="meta_past.xml" title="The Past">
                <p>My previous and futile attempts at building a personal web
                site.</p>
            </subsection>
            <subsection href="meta_present.xml" title="The Present">
                <p>How I built up this web site. Behind the simple looks of
                these pages lies a design elegance. Really.</p>
            </subsection>
            <subsection href="meta_future.xml" title="The Future">
                <p>Some things are unfinished, but then "release early, release
                often" they would say...</p>
            </subsection>
            <subsection href="meta_html5.xml" title="The Future is HTML5">
                <p>... And eventually I rewrote the web site using HTML5.</p>
            </subsection>
            <subsection href="meta_blog.xml" title="The Static Blog">
                <p>I also moved my blog to this site. This is why and how.</p>
            </subsection>
            <subsection href="meta_simplifications.xml" title="Simplifications">
                <p>Since 2023, I simplified the building and deployment of this web site.</p>
            </subsection>
        </section>
    </body>

</page>
